default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>

development:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
test:
  <<: *default
